spring.datasource.url=jdbc:mysql://localhost:3306/finance?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=8084

spring.main.allow-bean-definition-overriding=true

application.security.jwt.secret-key=6dc61ea78fb65f94fb22c249a0fb569d4c0da19e723303468e2d5fddaa15850d
application.security.jwt.expiration=86400000
#application.security.jwt.refresh.expiration=604800000

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=tektaitheoriginals@gmail.com
spring.mail.password=mqdx ouoy afnk sxlk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.ssl.enable=true

logging.level.org.springframework.mail=info
payme.api.key=c90f3b5f2d4ae78efa0c0dfe8c9a4a9a05e34513
payme.api.url=https://sandbox.paymee.tn/api/v2/payments/create
binance.api.key=vvChur54UGQGRLdeBwbJK1vtTYmnivCxT7mnZogenv72QanfDC6roCVkJWpqSNJa
binance.api.secret=4XBOdwJuSiAjYaweX5BAzbxFqVQ2jImgWYQnYBcrPfPwliFPjv9FtYavKVOuic2t
